name: CICD Static Deploymwnt

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST}}
          username: ${{ secret.SSH_USERNAME}}
          key:  ${{ secret.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/stopwatch
            sudo git pull origin main
            echo "Done"
